name: 🔄 Sync master to next

on:
  pull_request:
    types: [closed]
    branches: [master, main]

permissions:
  contents: write
  pull-requests: write
  issues: write

env:
  BASE_BRANCH: main
  TARGET_BRANCH: next
  SYNC_BRANCH_PREFIX: sync-ghcli-
  GH_TOKEN: ${{ secrets.PR_AUTOMATION_BOT_TOKEN }}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BASE_BRANCH }}

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh jq

      - name: Get last merged PR
        id: last_pr
        run: |
          LAST_PR=$(gh pr list \
            --base $BASE_BRANCH \
            --state merged \
            --limit 1 \
            --sort merged_at \
            --json number \
            -q '.[0].number')

          if [ -z "$LAST_PR" ]; then
            echo "No merged PRs found. Exiting."
            exit 0
          fi

          echo "LAST_PR=$LAST_PR" >> $GITHUB_ENV
          echo "Last merged PR: $LAST_PR"

      - name: Get commits from last PR
        run: |
          COMMITS=$(gh pr view $LAST_PR --json commits -q '.commits[].oid')

          if [ -z "$COMMITS" ]; then
            echo "No commits found in PR #$LAST_PR. Exiting."
            exit 0
          fi

          echo "COMMITS=$COMMITS" >> $GITHUB_ENV
          echo "Commits to consider: $COMMITS"

      - name: Prepare sync branch
        run: |
          SYNC_BRANCH=${SYNC_BRANCH_PREFIX}$(date +%s)
          echo "SYNC_BRANCH=$SYNC_BRANCH" >> $GITHUB_ENV

          git fetch origin $TARGET_BRANCH
          git checkout -b $SYNC_BRANCH origin/$TARGET_BRANCH

          for commit in $COMMITS; do
            git cherry-pick $commit || (echo "Conflict while cherry-picking $commit" && exit 1)
          done

          git push origin $SYNC_BRANCH

      - name: Create PR
        run: |
          gh pr create \
            --base $TARGET_BRANCH \
            --head $SYNC_BRANCH \
            --title "🔄 Sync $BASE_BRANCH to $TARGET_BRANCH" \
            --body "This PR syncs the latest changes from $BASE_BRANCH to $TARGET_BRANCH."
