name: 🔄 Sync master to next (GH CLI)

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write
  pull-requests: write

env:
  TARGET_BRANCH: next
  SYNC_BRANCH_PREFIX: sync-ghcli-

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch full history for cherry-pick

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Determine new sync branch
        id: branch
        run: |
          DATE=$(date +%s)
          SYNC_BRANCH="${SYNC_BRANCH_PREFIX}${DATE}"
          echo "SYNC_BRANCH=$SYNC_BRANCH" >> $GITHUB_ENV
          echo "Created sync branch: $SYNC_BRANCH"

      - name: Create and switch to sync branch
        run: git checkout -b $SYNC_BRANCH ${{ github.ref }}

      - name: Fetch last merged PR into ${{ env.TARGET_BRANCH }}
        id: last_pr
        run: |
          LAST_PR=$(gh pr list --base ${{ env.TARGET_BRANCH }} --state merged --sort merged --limit 1 --json number -q '.[0].number')
          echo "LAST_PR=$LAST_PR" >> $GITHUB_ENV
          echo "Last merged PR into ${{ env.TARGET_BRANCH }}: #$LAST_PR"

      - name: Get commits from last PR
        id: commits
        run: |
          COMMITS=$(gh pr view $LAST_PR --json commits -q '.commits[].oid')
          echo "COMMITS=$COMMITS" >> $GITHUB_ENV
          echo "Commits to consider: $COMMITS"

      - name: Cherry-pick commits (skip [skip ci], workflow files, pom.xml only)
        run: |
          for commit in $COMMITS; do
            MESSAGE=$(git log -1 --pretty=%B $commit)
            FILES_CHANGED=$(git diff-tree --no-commit-id --name-only -r $commit)

            if [[ "$MESSAGE" =~ \[skip\ ci\] ]]; then
              echo "Skipping $commit because of [skip ci]"
              continue
            fi

            if echo "$FILES_CHANGED" | grep -q "^.github/workflows/sync-master-to-next.yml$"; then
              echo "Skipping $commit because it modifies the sync workflow"
              continue
            fi

            if ! echo "$FILES_CHANGED" | grep -v -E "pom\.xml" | grep -q '.'; then
              echo "Skipping $commit because it only modifies pom.xml files"
              continue
            fi

            git cherry-pick $commit || git cherry-pick --skip
          done

      - name: Push sync branch
        run: git push origin HEAD:$SYNC_BRANCH

      - name: Create pull request if commits exist
        id: pr
        run: |
          COMMITS_ON_BRANCH=$(git log ${{ env.TARGET_BRANCH }}..HEAD --oneline)
          if [ -z "$COMMITS_ON_BRANCH" ]; then
            echo "No commits to sync. Skipping PR creation."
            echo "PR_CREATED=false" >> $GITHUB_ENV
          else
            gh pr create \
              --title "Sync master → ${{ env.TARGET_BRANCH }}" \
              --body "Automated PR from GitHub Actions to sync master → ${{ env.TARGET_BRANCH }}" \
              --base ${{ env.TARGET_BRANCH }} \
              --head $SYNC_BRANCH
            echo "PR_CREATED=true" >> $GITHUB_ENV

      - name: Delete sync branch (always)
        if: always()
        run: |
          echo "Deleting sync branch $SYNC_BRANCH from remote (even if previous steps failed)"
          git push origin --delete $SYNC_BRANCH || true
          git branch -D $SYNC_BRANCH || true
